/* eslint-disable @typescript-eslint/no-explicit-any -- synthetic API fixtures are validated through visible behavior. */
import {test,expect,type Page} from "@playwright/test";
const groupId="ux-group";
function group(quota=1){return {id:groupId,name:"함께 푸는 그룹",is_owner:true,member_limit:8,revision:1,active_members:1,reserved_invites:0,settings_json:JSON.stringify({areaSeconds:{언어이해:45,자료해석:45,창의수리:45,언어추리:45,수열추리:45},repeatPolicy:"allow",advanceTimePolicy:"carry_remaining"}),lobby:{quotaRemaining:quota,quotaTotal:1,effectiveQuestionCount:15}};}
async function lobby(page:Page,quota=1,post?:(route:any,body:any)=>Promise<void>){let detail=group(quota);let reads=0;await page.route("**/api/group-exams**",async route=>{const req=route.request(),url=new URL(req.url());if(req.method()==="POST"){const body=req.postDataJSON();if(body.action==="presence-heartbeat")return route.fulfill({json:{phase:"idle",presence:[],serverNow:new Date().toISOString()}});if(post)return post(route,body);if(body.action==="settings-update"){await new Promise(resolve=>setTimeout(resolve,600));detail={...detail,revision:detail.revision+1,member_limit:body.memberLimit,settings_json:JSON.stringify(body.settings)};return route.fulfill({json:{updated:true,settings:{member_limit:detail.member_limit,settings_json:detail.settings_json,revision:detail.revision}}});}if(body.action==="invite-create"){expect(body.reusable).toBe(true);await new Promise(resolve=>setTimeout(resolve,500));return route.fulfill({status:201,json:{invite:{token:"synthetic-shared-token",reusable:true}}});}return route.fulfill({json:{ok:true}});}
 const scope=url.searchParams.get("scope");if(scope==="groups"||scope==="group")reads++;
 if(scope==="sync")return route.fulfill({json:{groupId,phase:"idle",run:null,presence:[]}});
 if(scope==="group")return route.fulfill({json:{group:detail,members:[{membership_id:"self",public_name:"대표",is_owner:true}]}});
 return route.fulfill({json:{groups:[{id:groupId,name:detail.name,recent_run_status:"completed",recent_run_id:"ux-result"}],ownedActiveCount:1,capabilities:{personalProgress:true,strictRepeat:true,webSocket:false},selectedGroupId:groupId,detail:{group:detail,members:[{membership_id:"self",public_name:"대표",is_owner:true}]},sync:{groupId,phase:"idle",presence:[]}}});});await page.goto("/groups");await expect(page.getByRole("heading",{name:detail.name,exact:true})).toBeVisible();return ()=>reads;}
test("quota exhaustion disables start and removes the manual state button",async({page})=>{await lobby(page,0);await expect(page.getByRole("button",{name:"오늘 응시 완료",exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:"상태 지금 확인"})).toHaveCount(0);});
test("settings show immediate saving and clear success without internal controls or extra reads",async({page},info)=>{const reads=await lobby(page);await page.getByRole("button",{name:"그룹 설정",exact:true}).click();const modal=page.getByRole("dialog");await modal.getByLabel("정원",{exact:true}).fill("12");await modal.getByRole("button",{name:"설정 저장",exact:true}).click();await expect(modal.getByRole("button",{name:"저장 중…",exact:true})).toBeDisabled();await expect(modal).not.toContainText("보류된 저장");await expect(modal).not.toContainText("같은 값 다시 저장");await expect(modal.getByText("✓ 설정을 저장했습니다.",{exact:true})).toBeVisible();expect(reads()).toBe(0);
 for(const width of [1280,390]){await page.setViewportSize({width,height:900});await expect(modal).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:info.outputPath(`settings-${width}.png`)});}
 await modal.getByRole("button",{name:"닫기",exact:true}).click();await expect(page.getByText(/정원 12명/)).toBeVisible();});
test("shared invite has spaced copy actions, reopens instantly, and deletion uses a plain irreversible confirmation",async({page},info)=>{await page.context().grantPermissions(["clipboard-read","clipboard-write"]);const reads=await lobby(page);await page.getByRole("button",{name:"초대 링크",exact:true}).click();let modal=page.getByRole("dialog");await expect(modal).toContainText("여러 사람");await modal.getByRole("button",{name:"초대 링크 만들기",exact:true}).click();await expect(modal.getByRole("button",{name:"링크 만드는 중…"})).toBeDisabled();await expect(modal.getByRole("textbox")).toHaveValue(/synthetic-shared-token/);expect(reads()).toBe(0);await modal.getByRole("button",{name:"링크 복사",exact:true}).click();await expect(modal.getByRole("button",{name:"복사됨 ✓",exact:true})).toBeVisible();
 for(const width of [1280,390]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:info.outputPath(`invite-${width}.png`)});}
 await modal.getByRole("button",{name:"닫기",exact:true}).click();await page.getByRole("button",{name:"초대 링크",exact:true}).click();await expect(page.getByRole("dialog").getByRole("textbox")).toHaveValue(/synthetic-shared-token/);await page.getByRole("dialog").getByRole("button",{name:"닫기",exact:true}).click();await page.getByRole("button",{name:"그룹 삭제",exact:true}).click();modal=page.getByRole("dialog");await expect(modal).toContainText("되돌릴 수 없습니다");await expect(modal).not.toContainText("감사 기록");await modal.getByRole("textbox").fill("함께 푸는 그룹");await expect(modal.getByRole("button",{name:"그룹 삭제",exact:true})).toBeEnabled();await page.screenshot({path:info.outputPath("delete-mobile.png")});});
test("slow start preparation still opens at five with no repeated current read on navigation",async({page})=>{let until=0,reads=0;await lobby(page,1,async(route,body)=>{if(body.action==="run-start"){await new Promise(resolve=>setTimeout(resolve,900));until=Date.now()+5000;return route.fulfill({status:201,json:{run:{id:"ux-countdown"},current:{serverNow:new Date().toISOString(),phase:"countdown",countdownEndsAt:new Date(until).toISOString(),participantStatus:"in_progress",run:{id:"ux-countdown",status:"running",questionCount:15,contractVersion:2},progress:{position:0,revision:0},question:null}}});}return route.fulfill({json:{ok:true}});});await page.route("**/api/group-exams?scope=current**",route=>{reads++;return route.fulfill({json:{serverNow:new Date().toISOString(),phase:"countdown",countdownEndsAt:new Date(until).toISOString(),participantStatus:"in_progress",run:{id:"ux-countdown",status:"running",questionCount:15,contractVersion:2},progress:{position:0,revision:0},question:null}});});await page.getByRole("button",{name:"시험 시작",exact:true}).click();await page.getByRole("button",{name:"지금 시작",exact:true}).click();await expect(page.getByRole("button",{name:"시험 준비 중…"})).toBeDisabled();await expect(page).toHaveURL(/groups\/exams\/ux-countdown/);await expect(page.locator("main strong").filter({hasText:/^5$/})).toBeVisible();expect(reads).toBe(0);});
test("separate result page shows complete questions with red chosen mistakes, green answers, then explanations and intact ranges",async({page},info)=>{const result={questionStats:[{position:0,participantCount:4,correctCount:1,unansweredCount:1},{position:1,participantCount:4,correctCount:2,unansweredCount:0}],run:{id:"ux-result",completedAt:new Date().toISOString()},orderedResults:[{rank:1,participantId:"me",publicName:"대표",self:true,correctCount:1,incorrectCount:1,unansweredCount:0}],review:[{position:0,area:"언어추리",prompt:"A~E는 각각 1~5의 순서입니다. 검증용 조건을 고르세요.",choices:["잘못 고른 보기","정답 보기","세 번째 보기"],answer:[0],correctAnswers:[1],explanation:"두 조건을 함께 적용하면 두 번째 보기가 성립합니다.",assets:[]},{position:1,area:"자료해석",prompt:"두 번째 검증 문항",choices:["정답","오답"],answer:[0],correctAnswers:[0],explanation:"올바르게 골랐습니다.",assets:[]}]};await page.route("**/api/group-exams?scope=result**",route=>route.fulfill({json:result}));await page.goto("/groups/results/ux-result");await expect(page.getByRole("heading",{name:"그룹 시험 결과",exact:true})).toBeVisible();await expect(page.getByText("A~E는 각각 1~5의 순서입니다.",{exact:true})).toBeVisible();await expect(page.getByRole("region",{name:"문제 지시문"})).toContainText("검증용 조건을 고르세요.");await expect(page.locator("del")).toHaveCount(0);await expect(page.getByRole("region",{name:"그룹 문항별 정답률"})).toContainText("25%");await expect(page.getByText("그룹 정답률 25%",{exact:false})).toBeVisible();const wrong=page.getByText("잘못 고른 보기",{exact:true}).locator("..");const right=page.getByText("정답 보기",{exact:true}).locator("..");expect(await wrong.evaluate(e=>getComputedStyle(e).backgroundColor)).toBe("rgb(255, 242, 240)");expect(await right.evaluate(e=>getComputedStyle(e).backgroundColor)).toBe("rgb(237, 247, 239)");await expect(wrong).toContainText("내 선택 · 오답");await expect(right).toContainText("정답");await expect(page.getByRole("region",{name:"문항 해설"})).toContainText("두 조건을 함께 적용");for(const width of [1280,390,320]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);if(width!==320)await page.screenshot({path:info.outputPath(`result-${width}.png`),fullPage:true});}await page.getByRole("button",{name:"전체 문항",exact:true}).click();await page.getByRole("button",{name:"2번 문항 복습"}).click();await expect(page.getByText("두 번째 검증 문항")).toBeVisible();});

 test("deleted group leaves the detail immediately and shows a useful empty view",async({page},info)=>{
 let deleted=false,staleReads=0;
 await page.route("**/api/group-exams**",async route=>{const req=route.request(),scope=new URL(req.url()).searchParams.get("scope");
  if(req.method()==="POST"){const body=req.postDataJSON();if(body.action==="group-delete"){deleted=true;return route.fulfill({json:{deleted:true}});}return route.fulfill({json:{phase:"idle",presence:[],serverNow:new Date().toISOString()}});}
  if(scope==="group"||scope==="sync"){if(deleted){staleReads++;return route.fulfill({status:404,json:{code:"GROUP_NOT_FOUND",error:"그룹을 찾을 수 없습니다."}});}return route.fulfill({json:scope==="sync"?{groupId,phase:"idle",run:null,presence:[]}:{group:group(),members:[]}});}
  if(deleted){await new Promise(r=>setTimeout(r,700));return route.fulfill({json:{groups:[],ownedActiveCount:0,capabilities:{personalProgress:true,webSocket:false}}});}
  return route.fulfill({json:{groups:[{id:groupId,name:"함께 푸는 그룹"}],ownedActiveCount:1,capabilities:{personalProgress:true,webSocket:false},selectedGroupId:groupId,detail:{group:group(),members:[{public_name:"대표",is_owner:true}]},sync:{groupId,phase:"idle",presence:[]}}});
 });
 await page.goto("/groups");await page.getByRole("button",{name:"그룹 삭제",exact:true}).click();await page.getByRole("dialog").getByRole("textbox").fill("함께 푸는 그룹");await page.getByRole("dialog").getByRole("button",{name:"그룹 삭제",exact:true}).click();
 await expect(page.getByRole("heading",{name:"첫 그룹을 만들어 함께 풀어 보세요",exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"함께 푸는 그룹",exact:true})).toHaveCount(0);await page.waitForTimeout(1200);expect(staleReads).toBe(0);await expect(page.getByText("그룹을 찾을 수 없습니다.",{exact:true})).toHaveCount(0);
 for(const width of [1280,390,320]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);if(width!==320)await page.screenshot({path:info.outputPath(`empty-${width}.png`),fullPage:true});}
 await page.getByRole("button",{name:"새 그룹 만들기",exact:true}).click();await expect(page.getByLabel("그룹 이름",{exact:true})).toBeFocused();
 });

test("deletion selects the next remaining group without restoring the deleted detail",async({page})=>{
 const next={...group(),id:"next-group",name:"다음 그룹"};let deleted=false;
 await page.route("**/api/group-exams**",route=>{const req=route.request(),url=new URL(req.url()),scope=url.searchParams.get("scope");if(req.method()==="POST"){if(req.postDataJSON().action==="group-delete")deleted=true;return route.fulfill({json:{phase:"idle",presence:[],serverNow:new Date().toISOString()}});}
 if(scope==="group")return route.fulfill({json:{group:next,members:[]}});if(scope==="sync")return route.fulfill({json:{groupId:url.searchParams.get("groupId"),phase:"idle",run:null,presence:[]}});
 return route.fulfill({json:{groups:deleted?[next]:[group(),next],ownedActiveCount:deleted?1:2,selectedGroupId:groupId,capabilities:{webSocket:false},detail:{group:group(),members:[]},sync:{groupId,phase:"idle",presence:[]}}});});
 await page.goto("/groups");await page.getByRole("button",{name:"그룹 삭제",exact:true}).click();await page.getByRole("dialog").getByRole("textbox").fill("함께 푸는 그룹");await page.getByRole("dialog").getByRole("button",{name:"그룹 삭제",exact:true}).click();await expect(page.getByRole("heading",{name:"다음 그룹",exact:true})).toBeVisible();await expect(page.getByRole("combobox")).toHaveValue("next-group");await expect(page.getByRole("heading",{name:"함께 푸는 그룹",exact:true})).toHaveCount(0);
});
