/* eslint-disable @typescript-eslint/no-explicit-any -- synthetic browser fixtures. */
import {test,expect} from '@playwright/test';
const groupId='ux3-group';const group=(count=1,owner=true)=>({id:groupId,name:'우리 그룹',public_name:'내 닉네임',active_members:count,member_limit:50,is_owner:owner,revision:2,settings_json:'{}',lobby:{quotaRemaining:1,quotaTotal:1,effectiveQuestionCount:15}});
async function lobby(page:any,{empty=false,count=1,owner=true}:{empty?:boolean;count?:number;owner?:boolean}={}){let name='내 닉네임';const actions:string[]=[];
 await page.route('**/api/group-exams**',async(route:any)=>{const req=route.request(),url=new URL(req.url()),scope=url.searchParams.get('scope');
  if(req.method()==='POST'){const body=req.postDataJSON();actions.push(body.action);if(body.action==='member-name-update'){await new Promise(r=>setTimeout(r,200));name=body.publicName;return route.fulfill({json:{publicName:name,revision:3}});}if(body.action==='group-leave'){empty=true;return route.fulfill({json:{status:'archived'}});}return route.fulfill({json:{phase:'idle',presence:[],serverNow:new Date().toISOString()}});}
  if(scope==='history'){if(url.searchParams.get('day')==='2026-09-28')return route.fulfill({json:{records:[],next:null}});return route.fulfill({json:{records:[{id:'history-new',created_at:'2026-09-29T15:14:00.000Z',actual_started_at_utc:'2026-09-29T15:14:05.000Z',status:'completed',participant_status:'submitted',score:8,question_count_snapshot:15},{id:'history-old',created_at:'2026-09-29T00:01:00.000Z',status:'completed',participant_status:'submitted',score:6,question_count_snapshot:15}],next:null}});}
  if(scope==='sync')return route.fulfill({json:{groupId,phase:'idle',run:null,presence:[]}});
  if(scope==='group')return route.fulfill({json:{group:{...group(count,owner),public_name:name},members:[{public_name:name,is_self:true,is_owner:owner}]}});
  return route.fulfill({json:{groups:empty?[]:[group(count,owner)],ownedActiveCount:empty?0:owner?1:0,capabilities:{webSocket:false},selectedGroupId:empty?'':groupId,detail:empty?null:{group:group(count,owner),members:[{public_name:name,is_self:true,is_owner:owner}]},sync:empty?null:{groupId,phase:'idle',presence:[]}}});
 });await page.goto('/groups');return actions;}

test('main navigation works and group creation opens a centered form with intuitive nickname guidance',async({page},info)=>{
 await lobby(page,{empty:true});await expect(page.getByRole('link',{name:'← 메인으로'})).toHaveAttribute('href','/');await page.getByRole('button',{name:'그룹 만들기',exact:true}).click();const modal=page.getByRole('dialog',{name:'새 그룹 만들기'});await expect(modal).toBeVisible();await expect(modal.getByLabel('그룹 이름',{exact:true})).toBeFocused();await expect(modal.getByLabel('그룹 닉네임',{exact:true})).toBeVisible();await expect(modal.getByText('이 그룹의 참가자 목록과 시험 결과에 표시되는 이름입니다.')).toBeVisible();
 for(const width of [1280,390]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:info.outputPath(`create-${width}.png`),fullPage:true});}await modal.getByRole('button',{name:'취소',exact:true}).click();await expect(modal).toHaveCount(0);await page.getByRole('link',{name:'← 메인으로'}).click();await expect(page).toHaveURL(/\/$/);
});
test('leaving alone asks confirmation and explains disappearance; cancellation never writes',async({page})=>{
 const actions=await lobby(page);await page.getByRole('button',{name:'그룹 나가기',exact:true}).click();const modal=page.getByRole('dialog',{name:'그룹 나가기'});await expect(modal.getByText(/마지막 참가자가 나가면 그룹이 사라지며/)).toBeVisible();expect(actions).not.toContain('group-leave');await modal.getByRole('button',{name:'취소'}).click();expect(actions).not.toContain('group-leave');await page.getByRole('button',{name:'그룹 나가기',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'그룹 나가기',exact:true}).click();await expect(page.getByRole('heading',{name:'첫 그룹을 만들어 함께 풀어 보세요'})).toBeVisible();expect(actions.filter(a=>a==='group-leave')).toHaveLength(1);
});
test('owner with peers must transfer ownership before leaving',async({page})=>{
 const actions=await lobby(page,{count:2});await page.getByRole('button',{name:'그룹 나가기',exact:true}).click();await expect(page.getByRole('dialog').getByText(/먼저 대표를 다른 그룹원에게 위임/)).toBeVisible();await expect(page.getByRole('dialog').getByRole('button',{name:'그룹 나가기',exact:true})).toBeDisabled();expect(actions).not.toContain('group-leave');
});
test('nickname changes immediately in my group and date-filtered exam records link to separate result pages',async({page},info)=>{
 await lobby(page);await page.getByRole('button',{name:'닉네임 변경'}).click();const modal=page.getByRole('dialog',{name:'그룹 닉네임 변경'});await expect(modal.getByLabel('그룹 닉네임',{exact:true})).toBeFocused();await modal.getByLabel('그룹 닉네임',{exact:true}).fill('바꾼 이름');await modal.getByRole('button',{name:'닉네임 저장'}).click();await expect(modal).toHaveCount(0);await expect(page.getByText('바꾼 이름',{exact:true})).toBeVisible();await expect(page.getByText('그룹 닉네임을 변경했습니다.')).toBeVisible();
 const history=page.getByRole('region',{name:'날짜별 내 응시 기록'});await expect(history.getByRole('link',{name:'결과 보기 →'})).toHaveCount(2);await expect(history.getByRole('link').first()).toHaveAttribute('href','/groups/results/history-new');await expect(history.getByText('15문항 · 8개 정답')).toBeVisible();await history.getByLabel('응시 날짜').fill('2026-09-28');await expect(history.getByText('이 날짜에는 응시 기록이 없습니다.')).toBeVisible();await history.getByRole('button',{name:'전체 날짜'}).click();await expect(history.getByRole('link')).toHaveCount(2);
 for(const width of [1280,390]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:info.outputPath(`lobby-history-${width}.png`),fullPage:true});}
});

test('a non-owner sees a leaving confirmation before any membership change',async({page})=>{const actions=await lobby(page,{count:2,owner:false});await page.getByRole('button',{name:'그룹 나가기',exact:true}).click();const modal=page.getByRole('dialog');await expect(modal.getByText('다시 참여하려면 초대 링크가 필요합니다.')).toBeVisible();await expect(modal.getByRole('button',{name:'그룹 나가기',exact:true})).toBeEnabled();expect(actions).not.toContain('group-leave');await modal.getByRole('button',{name:'취소'}).click();expect(actions).not.toContain('group-leave');});
