import { activateApprovedGroupBank } from "./helpers/approved-group-bank";
import assert from "node:assert/strict";
import test from "node:test";
import fs from "node:fs";
import {openCanonicalTestDatabase} from "./helpers/canonical-database.mjs";
import {sqliteD1} from "./helpers/sqlite-d1.mjs";
import {GET,POST,POST_ADMIN} from "../apps/backend/src/modules/group-exams/group-exam.service";
import {orderQuestionsByArea,SKCT_AREAS} from "../apps/backend/src/modules/group-exams/domain/group-exam.domain";

type ApiBody=Record<string,unknown>&{
  group:{id:string};
  run:{id:string};
  publicQuestionWindow:Array<Record<string,unknown>>;
};
const origin="https://example.test";let serial=0;
async function post(email:string,body:Record<string,unknown>,admin=false){const response=await(admin?POST_ADMIN:POST)(new Request(`${origin}/api/group-exams${admin?"/admin":""}`,{method:"POST",headers:{origin,"content-type":"application/json","x-baeumzip-authenticated-user-email":email,[admin?"x-sql-study-admin-request":"x-sql-study-user-request"]:"1"},body:JSON.stringify({idempotencyKey:`v4-request-${++serial}`, ...body})}));return{status:response.status,body:await response.json() as ApiBody};}
async function get(email:string,query:string){const response=await GET(new Request(`${origin}/api/group-exams?${query}`,{headers:{"x-baeumzip-authenticated-user-email":email}}));return{status:response.status,body:await response.json() as ApiBody};}
async function seed(db: ReturnType<typeof openCanonicalTestDatabase>) { await activateApprovedGroupBank(db); }

test("new runs seal canonical area order and enforce one shared countdown",async()=>{const db=openCanonicalTestDatabase(process.cwd());const previous=globalThis.__BAEUMZIP_ENV__;globalThis.__BAEUMZIP_ENV__={DB:sqliteD1(db) as unknown as D1Database,SKCT_GROUP_SERVICE_ENABLED:"1",SKCT_GROUP_V2_ENABLED:"1",SKCT_GROUP_REPEAT_IDENTITY_VERIFIED:"1"};try{await seed(db);const owner="v4-owner@example.test";const created=await post(owner,{action:"group-create",name:"순서 검증",publicName:"대표"});assert.equal(created.status,201,JSON.stringify(created));const groupId=String(created.body.group.id);db.prepare("UPDATE study_groups SET admin_question_count_override=15 WHERE id=?").run(groupId);const started=await post(owner,{action:"run-start",groupId,mode:"immediate"});assert.equal(started.status,201,JSON.stringify(started));const runId=String(started.body.run.id);const countdown=await get(owner,`scope=current&runId=${runId}`);assert.equal(countdown.body.phase,"countdown");assert.equal(countdown.body.question,null);assert.deepEqual(countdown.body.publicQuestionWindow,[]);const rejected=await post(owner,{action:"question-advance",runId,position:0,expectedProgressRevision:0,answers:[0],expectedAnswerRevision:0});assert.equal(rejected.status,409);const areas=(db.prepare("SELECT area_code_snapshot FROM study_group_exam_question_public WHERE run_id=? ORDER BY position").all(runId) as Array<{area_code_snapshot:string}>).map(row=>row.area_code_snapshot);assert.deepEqual(areas,[...areas].sort((a,b)=>SKCT_AREAS.indexOf(a as typeof SKCT_AREAS[number])-SKCT_AREAS.indexOf(b as typeof SKCT_AREAS[number])));const now=Date.now();db.prepare("UPDATE study_group_exam_runs SET actual_started_at_utc=?,final_deadline_at_utc=? WHERE id=?").run(new Date(now-1000).toISOString(),new Date(now+900000).toISOString(),runId);db.prepare("UPDATE study_group_exam_participant_progress SET current_opened_at_utc=?,current_deadline_at_utc=?,started_at_utc=? WHERE run_id=?").run(new Date(now-1000).toISOString(),new Date(now+44000).toISOString(),new Date(now-1000).toISOString(),runId);const current=await get(owner,`scope=current&runId=${runId}`);assert.equal(current.status,200);assert.equal(current.body.publicQuestionWindow.length,1);assert.doesNotMatch(JSON.stringify(current.body),/TOP SECRET|correct_answers|explanation_snapshot/u);const advanced=await post(owner,{action:"question-advance",runId,position:0,expectedProgressRevision:0,answers:[0],expectedAnswerRevision:0});assert.equal(advanced.status,200,JSON.stringify(advanced));assert.equal(advanced.body.position,1);assert.equal(advanced.body.publicQuestionWindow.length,1);assert.equal(advanced.body.publicQuestionWindow[0].position,1);assert.equal((await get(owner,`scope=result&runId=${runId}`)).status,404);}finally{db.close();globalThis.__BAEUMZIP_ENV__=previous;}});

test("scheduling is gone and group deletion is an audited soft archive",async()=>{const db=openCanonicalTestDatabase(process.cwd());const previous=globalThis.__BAEUMZIP_ENV__;globalThis.__BAEUMZIP_ENV__={DB:sqliteD1(db) as unknown as D1Database,SKCT_GROUP_SERVICE_ENABLED:"1",SKCT_GROUP_V2_ENABLED:"1",SKCT_GROUP_REPEAT_IDENTITY_VERIFIED:"1",ADMIN_EMAIL:"admin@example.test"};try{await seed(db);const owner="delete-owner@example.test";const created=await post(owner,{action:"group-create",name:"삭제 확인 그룹",publicName:"대표"});assert.equal(created.status,201,JSON.stringify(created));const groupId=String(created.body.group.id);assert.equal((await post(owner,{action:"run-start",groupId,mode:"scheduled",scheduledAt:new Date(Date.now()+60000).toISOString()})).status,410);assert.equal(db.prepare("SELECT COUNT(*) n FROM study_group_exam_runs WHERE group_id=?").get(groupId)?.n,0);const wrong=await post("admin@example.test",{action:"group-delete",groupId,expectedRevision:0,confirmedName:"다른 이름"},true);assert.equal(wrong.status,409);const deleted=await post("admin@example.test",{action:"group-delete",groupId,expectedRevision:0,confirmedName:"삭제 확인 그룹"},true);assert.equal(deleted.status,200,JSON.stringify(deleted));assert.equal(db.prepare("SELECT status FROM study_groups WHERE id=?").get(groupId)?.status,"archived");assert.equal(db.prepare("SELECT COUNT(*) n FROM study_group_members WHERE group_id=? AND status='active'").get(groupId)?.n,0);assert.equal(db.prepare("SELECT COUNT(*) n FROM study_group_owner_slots WHERE group_id=?").get(groupId)?.n,0);assert.equal(db.prepare("SELECT COUNT(*) n FROM admin_audit_logs WHERE target_id=? AND action='skct_group_deleted'").get(groupId)?.n,1);
const running=await post(owner,{action:"group-create",name:"진행 중 보존",publicName:"대표"});const runningId=String(running.body.group.id);assert.equal((await post(owner,{action:"run-start",groupId:runningId,mode:"immediate"})).status,201);assert.equal((await post(owner,{action:"group-delete",groupId:runningId,expectedRevision:0,confirmedName:"진행 중 보존"})).status,409);assert.equal((await post("admin@example.test",{action:"group-delete",groupId:runningId,expectedRevision:0,confirmedName:"진행 중 보존"},true)).status,409);assert.equal(db.prepare("SELECT status FROM study_groups WHERE id=?").get(runningId)?.status,"active");
const last=await post("last-owner@example.test",{action:"group-create",name:"마지막 탈퇴",publicName:"대표"});const lastId=String(last.body.group.id);assert.equal((await post("last-owner@example.test",{action:"group-leave",groupId:lastId})).body.status,"archived");assert.equal(db.prepare("SELECT status FROM study_groups WHERE id=?").get(lastId)?.status,"archived");}finally{db.close();globalThis.__BAEUMZIP_ENV__=previous;}});

test("client contract is dedicated, durable and reveals only the server-started question",()=>{const runner=fs.readFileSync("apps/frontend/src/features/group-exams/group-exam-runner-client.tsx","utf8");const queue=fs.readFileSync("apps/frontend/src/features/group-exams/group-exam-queue.ts","utf8");const lobby=fs.readFileSync("apps/frontend/src/features/group-exams/group-exam-client.tsx","utf8");const repository=fs.readFileSync("apps/backend/src/modules/group-exams/group-exam-v2.repository.ts","utf8");assert.doesNotMatch(runner,/setDisplay\(next\)|position\+1/u);assert.match(runner,/putQueue|claimQueue/u);assert.match(queue,/existing\.payloadDigest!==item\.payloadDigest/u);assert.match(runner,/동기화 중/u);assert.match(runner,/Boolean\(pending\).*status==="syncing"/u);assert.doesNotMatch(lobby,/mode:\s*"scheduled"/u);assert.doesNotMatch(lobby,/scope=current|CurrentQuestion/u);const windowQuery=repository.slice(repository.indexOf("async publicWindow"),repository.indexOf("async mutateProgress"));assert.doesNotMatch(windowQuery,/question_secret|correct_answers|explanation/u);assert.match(windowQuery,/q\.position=\?/u);assert.doesNotMatch(windowQuery,/q\.position>=/u);assert.match(fs.readFileSync("apps/frontend/app/groups/exams/[runId]/page.tsx","utf8"),/robots:\{index:false/u);});

test("area ordering skips empty areas without changing in-area order",()=>{const input=[{id:"a",area:"수열추리" as const},{id:"b",area:"언어이해" as const},{id:"c",area:"수열추리" as const},{id:"d",area:"창의수리" as const}];assert.deepEqual(orderQuestionsByArea(input).map(row=>row.id),["b","d","a","c"]);});
