// Generated by scripts/generate-course-registry.mjs from course-registry.source.json.
// Do not edit this file directly.

export const COURSE_REGISTRY_SCHEMA_VERSION: 3;

export const DEFAULT_REGISTERED_EXAM_TYPE: "SQLP";

export const COURSE_FIELD_DEFINITIONS: readonly [
  Readonly<{
    readonly "id": "sql";
    readonly "engineId": "certification";
    readonly "name": "SQL";
    readonly "shortLabel": "SQL";
    readonly "cardTitle": "SQL 자격증";
    readonly "summary": "SQLD 기본 과정부터 SQLP 심화 과정까지 이론, 문제 풀이와 모의고사로 학습합니다.";
    readonly "status": "available";
  }>,
  Readonly<{
    readonly "id": "data-architecture";
    readonly "engineId": "certification";
    readonly "name": "데이터 아키텍처";
    readonly "shortLabel": "DA";
    readonly "brandSubtitleLines": readonly [
      "데이터 아키텍처",
      "자격 학습",
    ];
    readonly "cardTitle": "데이터 아키텍처 자격증";
    readonly "summary": "DAsP 기초 과정부터 DAP 전문가 과정까지 이론, 문제 풀이와 모의고사로 학습합니다.";
    readonly "status": "available";
  }>,
  Readonly<{
    readonly "id": "big-data-analysis";
    readonly "engineId": "certification";
    readonly "name": "빅데이터 분석";
    readonly "shortLabel": "BA";
    readonly "brandSubtitleLines": readonly [
      "빅데이터분석기사",
      "필기 학습",
    ];
    readonly "cardTitle": "빅데이터분석기사";
    readonly "summary": "빅데이터분석기사 필기 1·2·3·4과목과 실기 작업형 제1·2·3유형 로컬 실습을 학습합니다.";
    readonly "status": "available";
  }>,
  Readonly<{
    readonly "id": "information-processing";
    readonly "engineId": "certification";
    readonly "name": "정보처리";
    readonly "shortLabel": "정보처리";
    readonly "brandSubtitleLines": readonly [
      "정보처리기사",
      "필기·실기 학습",
    ];
    readonly "cardTitle": "정보처리기사";
    readonly "summary": "공통 핵심 이론은 함께 학습하고, 필기 객관식과 실기 필답형은 과정별 문제로 준비합니다.";
    readonly "status": "available";
  }>,
  Readonly<{
    readonly "id": "information-security";
    readonly "engineId": "certification";
    readonly "name": "정보보안";
    readonly "shortLabel": "보안";
    readonly "brandSubtitleLines": readonly [
      "정보보안기사",
      "필기·실기 학습",
    ];
    readonly "cardTitle": "정보보안기사";
    readonly "summary": "정보보안기사 필기와 실기를 과목별 이론과 문제로 학습할 수 있도록 준비하고 있습니다.";
    readonly "status": "available";
  }>,
];

export const SUBJECT_DEFINITIONS: readonly [
  Readonly<{
    readonly "id": "data-modeling";
    readonly "name": "데이터 모델링의 이해";
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "sql-basics";
    readonly "name": "SQL 기본 및 활용";
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "sql-advanced-tuning";
    readonly "name": "SQL 고급 활용 및 튜닝";
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "enterprise-architecture";
    readonly "name": "전사아키텍처 이해";
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "data-requirements";
    readonly "name": "데이터 요건 분석";
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "data-standardization";
    readonly "name": "데이터 표준화";
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "data-modeling-practice";
    readonly "name": "데이터 모델링";
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "database-design-and-use";
    readonly "name": "데이터베이스 설계와 이용";
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "data-quality-management";
    readonly "name": "데이터 품질 관리 이해";
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "big-data-analysis-planning";
    readonly "name": "빅데이터 분석기획";
    readonly "aliases": readonly [
      "빅데이터 분석 기획",
    ];
  }>,
  Readonly<{
    readonly "id": "big-data-exploration";
    readonly "name": "빅데이터 탐색";
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "big-data-modeling";
    readonly "name": "빅데이터 모델링";
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "big-data-result-interpretation";
    readonly "name": "빅데이터 결과 해석";
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "ipe-software-design";
    readonly "name": "소프트웨어 설계";
    readonly "aliases": readonly [
      "소프트웨어설계",
    ];
  }>,
  Readonly<{
    readonly "id": "ipe-software-development";
    readonly "name": "소프트웨어 개발";
    readonly "aliases": readonly [
      "소프트웨어개발",
    ];
  }>,
  Readonly<{
    readonly "id": "ipe-database-construction";
    readonly "name": "데이터베이스 구축";
    readonly "aliases": readonly [
      "데이터베이스구축",
    ];
  }>,
  Readonly<{
    readonly "id": "ipe-programming-language-utilization";
    readonly "name": "프로그래밍 언어 활용";
    readonly "aliases": readonly [
      "프로그래밍언어활용",
    ];
  }>,
  Readonly<{
    readonly "id": "ipe-information-system-construction-management";
    readonly "name": "정보시스템 구축 관리";
    readonly "aliases": readonly [
      "정보시스템구축관리",
    ];
  }>,
  Readonly<{
    readonly "id": "ipe-practical-work";
    readonly "name": "정보처리실무";
    readonly "aliases": readonly [
      "정보처리 실무",
    ];
  }>,
  Readonly<{
    readonly "id": "ise-system-security";
    readonly "name": "시스템보안";
    readonly "aliases": readonly [
      "시스템 보안",
    ];
  }>,
  Readonly<{
    readonly "id": "ise-network-security";
    readonly "name": "네트워크보안";
    readonly "aliases": readonly [
      "네트워크 보안",
    ];
  }>,
  Readonly<{
    readonly "id": "ise-application-security";
    readonly "name": "어플리케이션보안";
    readonly "aliases": readonly [
      "어플리케이션 보안",
      "애플리케이션 보안",
    ];
  }>,
  Readonly<{
    readonly "id": "ise-security-general";
    readonly "name": "정보보안일반";
    readonly "aliases": readonly [
      "정보보안 일반",
    ];
  }>,
  Readonly<{
    readonly "id": "ise-security-management-law";
    readonly "name": "정보보안관리 및 법규";
    readonly "aliases": readonly [
      "정보보안 관리 및 법규",
    ];
  }>,
  Readonly<{
    readonly "id": "ise-practical-work";
    readonly "name": "정보보안 실무";
    readonly "aliases": readonly [
      "정보보안실무",
    ];
  }>,
];

export const CONTENT_SCOPE_DEFINITIONS: readonly [
  Readonly<{
    readonly "id": "SQLD";
    readonly "courseExamTypes": readonly [
      "SQLD",
    ];
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "SQLP";
    readonly "courseExamTypes": readonly [
      "SQLP",
    ];
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "both";
    readonly "courseExamTypes": readonly [
      "SQLD",
      "SQLP",
    ];
    readonly "aliases": readonly [
      "common",
      "SQLD·SQLP",
      "SQLD/SQLP",
      "SQLD+SQLP",
      "SQLD&SQLP",
    ];
  }>,
  Readonly<{
    readonly "id": "DASP";
    readonly "courseExamTypes": readonly [
      "DASP",
    ];
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "DAP";
    readonly "courseExamTypes": readonly [
      "DAP",
    ];
    readonly "aliases": readonly [];
  }>,
  Readonly<{
    readonly "id": "DA";
    readonly "courseExamTypes": readonly [
      "DASP",
      "DAP",
    ];
    readonly "aliases": readonly [
      "DA_COMMON",
      "DA-COMMON",
      "DA COMMON",
      "DASP·DAP",
      "DASP/DAP",
      "DASP+DAP",
      "DASP&DAP",
    ];
  }>,
  Readonly<{
    readonly "id": "BAE";
    readonly "courseExamTypes": readonly [
      "BAE",
    ];
    readonly "aliases": readonly [
      "BIGDATA",
      "BIG-DATA",
      "BIG_DATA",
      "빅데이터분석기사",
      "빅분기",
    ];
  }>,
  Readonly<{
    readonly "id": "IPEW";
    readonly "courseExamTypes": readonly [
      "IPEW",
    ];
    readonly "aliases": readonly [
      "정보처리기사 필기",
      "정처기 필기",
    ];
  }>,
  Readonly<{
    readonly "id": "IPEP";
    readonly "courseExamTypes": readonly [
      "IPEP",
    ];
    readonly "aliases": readonly [
      "정보처리기사 실기",
      "정처기 실기",
    ];
  }>,
  Readonly<{
    readonly "id": "IPE";
    readonly "courseExamTypes": readonly [
      "IPEW",
      "IPEP",
    ];
    readonly "aliases": readonly [
      "IPE_COMMON",
      "IPE-COMMON",
      "IPE COMMON",
      "정보처리기사",
      "정보처리기사 공통",
      "정처기 공통",
    ];
  }>,
  Readonly<{
    readonly "id": "ISEW";
    readonly "courseExamTypes": readonly [
      "ISEW",
    ];
    readonly "aliases": readonly [
      "정보보안기사 필기",
      "보안기사 필기",
    ];
  }>,
  Readonly<{
    readonly "id": "ISEP";
    readonly "courseExamTypes": readonly [
      "ISEP",
    ];
    readonly "aliases": readonly [
      "정보보안기사 실기",
      "보안기사 실기",
    ];
  }>,
];

export const COURSE_DEFINITIONS: readonly [
  Readonly<{
    readonly "examType": "SQLD";
    readonly "fieldId": "sql";
    readonly "courseId": "sqld";
    readonly "name": "SQLD";
    readonly "releaseStage": "released";
    readonly "summary": "데이터 모델링과 SQL 기본·활용을 객관식 문제로 학습합니다.";
    readonly "studyMode": "2과목 · 객관식";
    readonly "mockExam": "50문항 · 90분";
    readonly "subjects": readonly [
      Readonly<{
        readonly "id": "data-modeling";
        readonly "name": "데이터 모델링의 이해";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "sql-basics";
        readonly "name": "SQL 기본 및 활용";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "releasedSubjects": readonly [
      Readonly<{
        readonly "id": "data-modeling";
        readonly "name": "데이터 모델링의 이해";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "sql-basics";
        readonly "name": "SQL 기본 및 활용";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "contentKinds": readonly [
      "theory",
      "question",
      "mock-exam",
    ];
    readonly "questionSubjects": readonly [
      Readonly<{
        readonly "id": "data-modeling";
        readonly "name": "데이터 모델링의 이해";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "sql-basics";
        readonly "name": "SQL 기본 및 활용";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "acceptedContentScopes": readonly [
      "SQLD",
      "both",
    ];
    readonly "descriptiveSubjects": readonly [];
    readonly "examPolicy": Readonly<{
      readonly "policyVersion": "dataq-2026-08-23";
      readonly "title": "SQLD 실전 모의고사";
      readonly "durationMinutes": 90;
      readonly "objectiveCounts": Readonly<{
        readonly "데이터 모델링의 이해": 10;
        readonly "SQL 기본 및 활용": 40;
      }>;
      readonly "descriptiveCount": 0;
      readonly "objectivePoint": 2;
      readonly "descriptivePoint": 0;
      readonly "totalQuestions": 50;
      readonly "totalPoints": 100;
      readonly "passingScore": 60;
      readonly "subjectMinimumRate": 40;
      readonly "practicalMinimumRate": 0;
      readonly "resultDecimals": 0;
    }>;
  }>,
  Readonly<{
    readonly "examType": "SQLP";
    readonly "fieldId": "sql";
    readonly "courseId": "sqlp";
    readonly "name": "SQLP";
    readonly "releaseStage": "released";
    readonly "summary": "SQL 기본부터 고급 활용·튜닝까지 이론과 실전 문제로 학습합니다.";
    readonly "studyMode": "3과목 · 객관식·서술형";
    readonly "mockExam": "72문항 · 180분";
    readonly "subjects": readonly [
      Readonly<{
        readonly "id": "data-modeling";
        readonly "name": "데이터 모델링의 이해";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "sql-basics";
        readonly "name": "SQL 기본 및 활용";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "sql-advanced-tuning";
        readonly "name": "SQL 고급 활용 및 튜닝";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "releasedSubjects": readonly [
      Readonly<{
        readonly "id": "data-modeling";
        readonly "name": "데이터 모델링의 이해";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "sql-basics";
        readonly "name": "SQL 기본 및 활용";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "sql-advanced-tuning";
        readonly "name": "SQL 고급 활용 및 튜닝";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "contentKinds": readonly [
      "theory",
      "question",
      "mock-exam",
    ];
    readonly "questionSubjects": readonly [
      Readonly<{
        readonly "id": "data-modeling";
        readonly "name": "데이터 모델링의 이해";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "sql-basics";
        readonly "name": "SQL 기본 및 활용";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "sql-advanced-tuning";
        readonly "name": "SQL 고급 활용 및 튜닝";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "acceptedContentScopes": readonly [
      "SQLP",
      "both",
    ];
    readonly "descriptiveSubjects": readonly [
      "SQL 고급 활용 및 튜닝",
    ];
    readonly "examPolicy": Readonly<{
      readonly "policyVersion": "dataq-2026-08-23";
      readonly "title": "SQLP 실전 모의고사";
      readonly "durationMinutes": 180;
      readonly "objectiveCounts": Readonly<{
        readonly "데이터 모델링의 이해": 10;
        readonly "SQL 기본 및 활용": 20;
        readonly "SQL 고급 활용 및 튜닝": 40;
      }>;
      readonly "descriptiveCount": 2;
      readonly "objectivePoint": 1;
      readonly "descriptivePoint": 15;
      readonly "totalQuestions": 72;
      readonly "totalPoints": 100;
      readonly "passingScore": 75;
      readonly "subjectMinimumRate": 40;
      readonly "practicalMinimumRate": 0;
      readonly "resultDecimals": 1;
    }>;
  }>,
  Readonly<{
    readonly "examType": "DASP";
    readonly "fieldId": "data-architecture";
    readonly "courseId": "dasp";
    readonly "name": "DAsP";
    readonly "releaseStage": "released";
    readonly "summary": "전사아키텍처부터 데이터 모델링까지 데이터아키텍처 기초를 학습합니다.";
    readonly "studyMode": "4과목 · 객관식";
    readonly "mockExam": "50문항 · 90분";
    readonly "subjects": readonly [
      Readonly<{
        readonly "id": "enterprise-architecture";
        readonly "name": "전사아키텍처 이해";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-requirements";
        readonly "name": "데이터 요건 분석";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-standardization";
        readonly "name": "데이터 표준화";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-modeling-practice";
        readonly "name": "데이터 모델링";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "releasedSubjects": readonly [
      Readonly<{
        readonly "id": "enterprise-architecture";
        readonly "name": "전사아키텍처 이해";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-requirements";
        readonly "name": "데이터 요건 분석";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-standardization";
        readonly "name": "데이터 표준화";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-modeling-practice";
        readonly "name": "데이터 모델링";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "contentKinds": readonly [
      "theory",
      "question",
      "mock-exam",
    ];
    readonly "questionSubjects": readonly [
      Readonly<{
        readonly "id": "enterprise-architecture";
        readonly "name": "전사아키텍처 이해";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-requirements";
        readonly "name": "데이터 요건 분석";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-standardization";
        readonly "name": "데이터 표준화";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-modeling-practice";
        readonly "name": "데이터 모델링";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "acceptedContentScopes": readonly [
      "DASP",
      "DA",
    ];
    readonly "descriptiveSubjects": readonly [];
    readonly "examPolicy": Readonly<{
      readonly "policyVersion": "dataq-2026-08-23";
      readonly "title": "DAsP 실전 모의고사";
      readonly "durationMinutes": 90;
      readonly "objectiveCounts": Readonly<{
        readonly "전사아키텍처 이해": 10;
        readonly "데이터 요건 분석": 10;
        readonly "데이터 표준화": 10;
        readonly "데이터 모델링": 20;
      }>;
      readonly "descriptiveCount": 0;
      readonly "objectivePoint": 2;
      readonly "descriptivePoint": 0;
      readonly "totalQuestions": 50;
      readonly "totalPoints": 100;
      readonly "passingScore": 60;
      readonly "subjectMinimumRate": 40;
      readonly "practicalMinimumRate": 0;
      readonly "resultDecimals": 0;
    }>;
  }>,
  Readonly<{
    readonly "examType": "DAP";
    readonly "fieldId": "data-architecture";
    readonly "courseId": "dap";
    readonly "name": "DAP";
    readonly "releaseStage": "released";
    readonly "summary": "데이터아키텍처 전 범위와 데이터 모델링 실무를 전문가 수준으로 학습합니다.";
    readonly "studyMode": "6과목 · 객관식·실기형";
    readonly "mockExam": "76문항 · 240분";
    readonly "subjects": readonly [
      Readonly<{
        readonly "id": "enterprise-architecture";
        readonly "name": "전사아키텍처 이해";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-requirements";
        readonly "name": "데이터 요건 분석";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-standardization";
        readonly "name": "데이터 표준화";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-modeling-practice";
        readonly "name": "데이터 모델링";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "database-design-and-use";
        readonly "name": "데이터베이스 설계와 이용";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-quality-management";
        readonly "name": "데이터 품질 관리 이해";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "releasedSubjects": readonly [
      Readonly<{
        readonly "id": "enterprise-architecture";
        readonly "name": "전사아키텍처 이해";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-requirements";
        readonly "name": "데이터 요건 분석";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-standardization";
        readonly "name": "데이터 표준화";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-modeling-practice";
        readonly "name": "데이터 모델링";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "database-design-and-use";
        readonly "name": "데이터베이스 설계와 이용";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-quality-management";
        readonly "name": "데이터 품질 관리 이해";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "contentKinds": readonly [
      "theory",
      "question",
      "mock-exam",
    ];
    readonly "questionSubjects": readonly [
      Readonly<{
        readonly "id": "enterprise-architecture";
        readonly "name": "전사아키텍처 이해";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-requirements";
        readonly "name": "데이터 요건 분석";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-standardization";
        readonly "name": "데이터 표준화";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-modeling-practice";
        readonly "name": "데이터 모델링";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "database-design-and-use";
        readonly "name": "데이터베이스 설계와 이용";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "data-quality-management";
        readonly "name": "데이터 품질 관리 이해";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "acceptedContentScopes": readonly [
      "DAP",
      "DA",
    ];
    readonly "descriptiveSubjects": readonly [
      "데이터 표준화",
      "데이터 모델링",
    ];
    readonly "examPolicy": Readonly<{
      readonly "policyVersion": "dataq-2026-08-23";
      readonly "title": "DAP 실전 모의고사";
      readonly "durationMinutes": 240;
      readonly "objectiveCounts": Readonly<{
        readonly "전사아키텍처 이해": 10;
        readonly "데이터 요건 분석": 10;
        readonly "데이터 표준화": 10;
        readonly "데이터 모델링": 25;
        readonly "데이터베이스 설계와 이용": 10;
        readonly "데이터 품질 관리 이해": 10;
      }>;
      readonly "descriptiveCount": 1;
      readonly "objectivePoint": 0.8;
      readonly "descriptivePoint": 40;
      readonly "totalQuestions": 76;
      readonly "totalPoints": 100;
      readonly "passingScore": 75;
      readonly "subjectMinimumRate": 40;
      readonly "practicalMinimumRate": 40;
      readonly "resultDecimals": 1;
    }>;
  }>,
  Readonly<{
    readonly "examType": "BAE";
    readonly "fieldId": "big-data-analysis";
    readonly "courseId": "bae-written";
    readonly "name": "빅데이터분석기사 필기";
    readonly "releaseStage": "released";
    readonly "summary": "1~4과목 핵심 이론을 학습하고, 전 과목 검수 완료 객관식 문제로 연습합니다.";
    readonly "studyMode": "1·2·3·4과목 이론 · 전 과목 문제";
    readonly "mockExam": "모의고사 준비 중";
    readonly "subjects": readonly [
      Readonly<{
        readonly "id": "big-data-analysis-planning";
        readonly "name": "빅데이터 분석기획";
        readonly "aliases": readonly [
          "빅데이터 분석 기획",
        ];
      }>,
      Readonly<{
        readonly "id": "big-data-exploration";
        readonly "name": "빅데이터 탐색";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "big-data-modeling";
        readonly "name": "빅데이터 모델링";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "big-data-result-interpretation";
        readonly "name": "빅데이터 결과 해석";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "releasedSubjects": readonly [
      Readonly<{
        readonly "id": "big-data-analysis-planning";
        readonly "name": "빅데이터 분석기획";
        readonly "aliases": readonly [
          "빅데이터 분석 기획",
        ];
      }>,
      Readonly<{
        readonly "id": "big-data-exploration";
        readonly "name": "빅데이터 탐색";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "big-data-modeling";
        readonly "name": "빅데이터 모델링";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "big-data-result-interpretation";
        readonly "name": "빅데이터 결과 해석";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "contentKinds": readonly [
      "theory",
      "question",
    ];
    readonly "questionSubjects": readonly [
      Readonly<{
        readonly "id": "big-data-analysis-planning";
        readonly "name": "빅데이터 분석기획";
        readonly "aliases": readonly [
          "빅데이터 분석 기획",
        ];
      }>,
      Readonly<{
        readonly "id": "big-data-exploration";
        readonly "name": "빅데이터 탐색";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "big-data-modeling";
        readonly "name": "빅데이터 모델링";
        readonly "aliases": readonly [];
      }>,
      Readonly<{
        readonly "id": "big-data-result-interpretation";
        readonly "name": "빅데이터 결과 해석";
        readonly "aliases": readonly [];
      }>,
    ];
    readonly "acceptedContentScopes": readonly [
      "BAE",
    ];
    readonly "descriptiveSubjects": readonly [];
    readonly "examPolicy": Readonly<{
      readonly "policyVersion": "dataq-bae-written-2022-brochure";
      readonly "title": "빅데이터분석기사 필기 실전 모의고사";
      readonly "durationMinutes": 120;
      readonly "objectiveCounts": Readonly<{
        readonly "빅데이터 분석기획": 20;
        readonly "빅데이터 탐색": 20;
        readonly "빅데이터 모델링": 20;
        readonly "빅데이터 결과 해석": 20;
      }>;
      readonly "descriptiveCount": 0;
      readonly "objectivePoint": 1.25;
      readonly "descriptivePoint": 0;
      readonly "totalQuestions": 80;
      readonly "totalPoints": 100;
      readonly "passingScore": 60;
      readonly "subjectMinimumRate": 40;
      readonly "practicalMinimumRate": 0;
      readonly "resultDecimals": 2;
    }>;
  }>,
  Readonly<{
    readonly "examType": "IPEW";
    readonly "fieldId": "information-processing";
    readonly "courseId": "ipe-written";
    readonly "name": "정보처리기사 필기";
    readonly "releaseStage": "released";
    readonly "summary": "1~5단원 이론과 객관식 문제로 학습합니다.";
    readonly "studyMode": "1~5단원 · 객관식";
    readonly "mockExam": "100문항 · 150분";
    readonly "subjects": readonly [
      Readonly<{
        readonly "id": "ipe-software-design";
        readonly "name": "소프트웨어 설계";
        readonly "aliases": readonly [
          "소프트웨어설계",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-software-development";
        readonly "name": "소프트웨어 개발";
        readonly "aliases": readonly [
          "소프트웨어개발",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-database-construction";
        readonly "name": "데이터베이스 구축";
        readonly "aliases": readonly [
          "데이터베이스구축",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-programming-language-utilization";
        readonly "name": "프로그래밍 언어 활용";
        readonly "aliases": readonly [
          "프로그래밍언어활용",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-information-system-construction-management";
        readonly "name": "정보시스템 구축 관리";
        readonly "aliases": readonly [
          "정보시스템구축관리",
        ];
      }>,
    ];
    readonly "releasedSubjects": readonly [
      Readonly<{
        readonly "id": "ipe-software-design";
        readonly "name": "소프트웨어 설계";
        readonly "aliases": readonly [
          "소프트웨어설계",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-software-development";
        readonly "name": "소프트웨어 개발";
        readonly "aliases": readonly [
          "소프트웨어개발",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-database-construction";
        readonly "name": "데이터베이스 구축";
        readonly "aliases": readonly [
          "데이터베이스구축",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-programming-language-utilization";
        readonly "name": "프로그래밍 언어 활용";
        readonly "aliases": readonly [
          "프로그래밍언어활용",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-information-system-construction-management";
        readonly "name": "정보시스템 구축 관리";
        readonly "aliases": readonly [
          "정보시스템구축관리",
        ];
      }>,
    ];
    readonly "contentKinds": readonly [
      "theory",
      "question",
      "mock-exam",
    ];
    readonly "questionSubjects": readonly [
      Readonly<{
        readonly "id": "ipe-software-design";
        readonly "name": "소프트웨어 설계";
        readonly "aliases": readonly [
          "소프트웨어설계",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-software-development";
        readonly "name": "소프트웨어 개발";
        readonly "aliases": readonly [
          "소프트웨어개발",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-database-construction";
        readonly "name": "데이터베이스 구축";
        readonly "aliases": readonly [
          "데이터베이스구축",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-programming-language-utilization";
        readonly "name": "프로그래밍 언어 활용";
        readonly "aliases": readonly [
          "프로그래밍언어활용",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-information-system-construction-management";
        readonly "name": "정보시스템 구축 관리";
        readonly "aliases": readonly [
          "정보시스템구축관리",
        ];
      }>,
    ];
    readonly "acceptedContentScopes": readonly [
      "IPEW",
      "IPE",
    ];
    readonly "descriptiveSubjects": readonly [];
    readonly "examPolicy": Readonly<{
      readonly "policyVersion": "qnet-ipe-written-2026";
      readonly "title": "정보처리기사 필기 실전 모의고사";
      readonly "durationMinutes": 150;
      readonly "objectiveCounts": Readonly<{
        readonly "소프트웨어 설계": 20;
        readonly "소프트웨어 개발": 20;
        readonly "데이터베이스 구축": 20;
        readonly "프로그래밍 언어 활용": 20;
        readonly "정보시스템 구축 관리": 20;
      }>;
      readonly "descriptiveCount": 0;
      readonly "objectivePoint": 1;
      readonly "descriptivePoint": 0;
      readonly "totalQuestions": 100;
      readonly "totalPoints": 100;
      readonly "passingScore": 60;
      readonly "subjectMinimumRate": 40;
      readonly "practicalMinimumRate": 0;
      readonly "resultDecimals": 0;
    }>;
  }>,
  Readonly<{
    readonly "examType": "IPEP";
    readonly "fieldId": "information-processing";
    readonly "courseId": "ipe-practical";
    readonly "name": "정보처리기사 실기";
    readonly "releaseStage": "released";
    readonly "summary": "코드 추적·SQL·계산·단답형에 필요한 실기 전용 이론과 창작 문제를 학습합니다.";
    readonly "studyMode": "정보처리실무 · 필답형";
    readonly "mockExam": "단답형 20문항 · 150분";
    readonly "subjects": readonly [
      Readonly<{
        readonly "id": "ipe-software-design";
        readonly "name": "소프트웨어 설계";
        readonly "aliases": readonly [
          "소프트웨어설계",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-software-development";
        readonly "name": "소프트웨어 개발";
        readonly "aliases": readonly [
          "소프트웨어개발",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-database-construction";
        readonly "name": "데이터베이스 구축";
        readonly "aliases": readonly [
          "데이터베이스구축",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-programming-language-utilization";
        readonly "name": "프로그래밍 언어 활용";
        readonly "aliases": readonly [
          "프로그래밍언어활용",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-information-system-construction-management";
        readonly "name": "정보시스템 구축 관리";
        readonly "aliases": readonly [
          "정보시스템구축관리",
        ];
      }>,
      Readonly<{
        readonly "id": "ipe-practical-work";
        readonly "name": "정보처리실무";
        readonly "aliases": readonly [
          "정보처리 실무",
        ];
      }>,
    ];
    readonly "releasedSubjects": readonly [
      Readonly<{
        readonly "id": "ipe-practical-work";
        readonly "name": "정보처리실무";
        readonly "aliases": readonly [
          "정보처리 실무",
        ];
      }>,
    ];
    readonly "contentKinds": readonly [
      "theory",
      "question",
      "mock-exam",
    ];
    readonly "questionSubjects": readonly [
      Readonly<{
        readonly "id": "ipe-practical-work";
        readonly "name": "정보처리실무";
        readonly "aliases": readonly [
          "정보처리 실무",
        ];
      }>,
    ];
    readonly "acceptedContentScopes": readonly [
      "IPEP",
      "IPE",
    ];
    readonly "descriptiveSubjects": readonly [
      "정보처리실무",
    ];
    readonly "examPolicy": Readonly<{
      readonly "policyVersion": "ipep-short-answer-2026-09-v1";
      readonly "title": "정보처리기사 실기 단답형 모의고사";
      readonly "durationMinutes": 150;
      readonly "objectiveCounts": Readonly<Record<string, never>>;
      readonly "descriptiveCount": 20;
      readonly "objectivePoint": 0;
      readonly "descriptivePoint": 5;
      readonly "totalQuestions": 20;
      readonly "totalPoints": 100;
      readonly "passingScore": 60;
      readonly "subjectMinimumRate": 0;
      readonly "practicalMinimumRate": 0;
      readonly "resultDecimals": 0;
    }>;
  }>,
  Readonly<{
    readonly "examType": "ISEW";
    readonly "fieldId": "information-security";
    readonly "courseId": "ise-written";
    readonly "name": "정보보안기사 필기";
    readonly "releaseStage": "released";
    readonly "summary": "시스템·네트워크·애플리케이션 보안부터 암호·접근통제, 정보보호 관리·법규까지 학습합니다.";
    readonly "studyMode": "필기 5과목 이론 · 시스템보안 문제";
    readonly "mockExam": "모의고사 준비 중";
    readonly "subjects": readonly [
      Readonly<{
        readonly "id": "ise-system-security";
        readonly "name": "시스템보안";
        readonly "aliases": readonly [
          "시스템 보안",
        ];
      }>,
      Readonly<{
        readonly "id": "ise-network-security";
        readonly "name": "네트워크보안";
        readonly "aliases": readonly [
          "네트워크 보안",
        ];
      }>,
      Readonly<{
        readonly "id": "ise-application-security";
        readonly "name": "어플리케이션보안";
        readonly "aliases": readonly [
          "어플리케이션 보안",
          "애플리케이션 보안",
        ];
      }>,
      Readonly<{
        readonly "id": "ise-security-general";
        readonly "name": "정보보안일반";
        readonly "aliases": readonly [
          "정보보안 일반",
        ];
      }>,
      Readonly<{
        readonly "id": "ise-security-management-law";
        readonly "name": "정보보안관리 및 법규";
        readonly "aliases": readonly [
          "정보보안 관리 및 법규",
        ];
      }>,
    ];
    readonly "releasedSubjects": readonly [
      Readonly<{
        readonly "id": "ise-system-security";
        readonly "name": "시스템보안";
        readonly "aliases": readonly [
          "시스템 보안",
        ];
      }>,
      Readonly<{
        readonly "id": "ise-network-security";
        readonly "name": "네트워크보안";
        readonly "aliases": readonly [
          "네트워크 보안",
        ];
      }>,
      Readonly<{
        readonly "id": "ise-application-security";
        readonly "name": "어플리케이션보안";
        readonly "aliases": readonly [
          "어플리케이션 보안",
          "애플리케이션 보안",
        ];
      }>,
      Readonly<{
        readonly "id": "ise-security-general";
        readonly "name": "정보보안일반";
        readonly "aliases": readonly [
          "정보보안 일반",
        ];
      }>,
      Readonly<{
        readonly "id": "ise-security-management-law";
        readonly "name": "정보보안관리 및 법규";
        readonly "aliases": readonly [
          "정보보안 관리 및 법규",
        ];
      }>,
    ];
    readonly "contentKinds": readonly [
      "theory",
      "question",
    ];
    readonly "questionSubjects": readonly [
      Readonly<{
        readonly "id": "ise-system-security";
        readonly "name": "시스템보안";
        readonly "aliases": readonly [
          "시스템 보안",
        ];
      }>,
    ];
    readonly "acceptedContentScopes": readonly [
      "ISEW",
    ];
    readonly "descriptiveSubjects": readonly [];
    readonly "examPolicy": Readonly<{
      readonly "policyVersion": "kca-ise-written-2023-2026";
      readonly "title": "정보보안기사 필기 실전 모의고사";
      readonly "durationMinutes": 150;
      readonly "objectiveCounts": Readonly<{
        readonly "시스템보안": 20;
        readonly "네트워크보안": 20;
        readonly "어플리케이션보안": 20;
        readonly "정보보안일반": 20;
        readonly "정보보안관리 및 법규": 20;
      }>;
      readonly "descriptiveCount": 0;
      readonly "objectivePoint": 1;
      readonly "descriptivePoint": 0;
      readonly "totalQuestions": 100;
      readonly "totalPoints": 100;
      readonly "passingScore": 60;
      readonly "subjectMinimumRate": 40;
      readonly "practicalMinimumRate": 0;
      readonly "resultDecimals": 0;
    }>;
  }>,
  Readonly<{
    readonly "examType": "ISEP";
    readonly "fieldId": "information-security";
    readonly "courseId": "ise-practical";
    readonly "name": "정보보안기사 실기";
    readonly "releaseStage": "intake";
    readonly "summary": "정보보안 실무 이론과 필답형 문제를 준비합니다.";
    readonly "studyMode": "정보보안 실무 · 필답형";
    readonly "mockExam": "모의고사 준비 중";
    readonly "subjects": readonly [
      Readonly<{
        readonly "id": "ise-practical-work";
        readonly "name": "정보보안 실무";
        readonly "aliases": readonly [
          "정보보안실무",
        ];
      }>,
    ];
    readonly "releasedSubjects": readonly [];
    readonly "contentKinds": readonly [];
    readonly "questionSubjects": readonly [];
    readonly "acceptedContentScopes": readonly [
      "ISEP",
    ];
    readonly "descriptiveSubjects": readonly [
      "정보보안 실무",
    ];
    readonly "examPolicy": null;
  }>,
];

export const LOCAL_PRACTICE_COURSES: readonly [
  Readonly<{
    readonly "courseId": "bae-practical";
    readonly "fieldId": "big-data-analysis";
    readonly "engineId": "certification";
    readonly "capability": "local-practice";
    readonly "name": "빅데이터분석기사 실기";
    readonly "summary": "실기 작업형 문제와 풀이를 학습합니다.";
    readonly "section": "type-1";
    readonly "sectionTitle": "작업형 제1유형";
    readonly "releaseKey": "bae-practical";
  }>,
];

export const REGISTERED_EXAM_TYPES: readonly [
  "SQLD",
  "SQLP",
  "DASP",
  "DAP",
  "BAE",
  "IPEW",
  "IPEP",
  "ISEW",
  "ISEP",
];

export const REGISTERED_CONTENT_SCOPES: readonly [
  "SQLD",
  "SQLP",
  "both",
  "DASP",
  "DAP",
  "DA",
  "BAE",
  "IPEW",
  "IPEP",
  "IPE",
  "ISEW",
  "ISEP",
];

export const REGISTERED_SUBJECTS: readonly [
  "데이터 모델링의 이해",
  "SQL 기본 및 활용",
  "SQL 고급 활용 및 튜닝",
  "전사아키텍처 이해",
  "데이터 요건 분석",
  "데이터 표준화",
  "데이터 모델링",
  "데이터베이스 설계와 이용",
  "데이터 품질 관리 이해",
  "빅데이터 분석기획",
  "빅데이터 탐색",
  "빅데이터 모델링",
  "빅데이터 결과 해석",
  "소프트웨어 설계",
  "소프트웨어 개발",
  "데이터베이스 구축",
  "프로그래밍 언어 활용",
  "정보시스템 구축 관리",
  "정보처리실무",
  "시스템보안",
  "네트워크보안",
  "어플리케이션보안",
  "정보보안일반",
  "정보보안관리 및 법규",
  "정보보안 실무",
];

export const REGISTERED_SUBJECT_IDS: readonly [
  "data-modeling",
  "sql-basics",
  "sql-advanced-tuning",
  "enterprise-architecture",
  "data-requirements",
  "data-standardization",
  "data-modeling-practice",
  "database-design-and-use",
  "data-quality-management",
  "big-data-analysis-planning",
  "big-data-exploration",
  "big-data-modeling",
  "big-data-result-interpretation",
  "ipe-software-design",
  "ipe-software-development",
  "ipe-database-construction",
  "ipe-programming-language-utilization",
  "ipe-information-system-construction-management",
  "ipe-practical-work",
  "ise-system-security",
  "ise-network-security",
  "ise-application-security",
  "ise-security-general",
  "ise-security-management-law",
  "ise-practical-work",
];

export const CONTENT_SCOPE_COURSES: Readonly<{
  readonly "SQLD": readonly [
    "SQLD",
  ];
  readonly "SQLP": readonly [
    "SQLP",
  ];
  readonly "both": readonly [
    "SQLD",
    "SQLP",
  ];
  readonly "DASP": readonly [
    "DASP",
  ];
  readonly "DAP": readonly [
    "DAP",
  ];
  readonly "DA": readonly [
    "DASP",
    "DAP",
  ];
  readonly "BAE": readonly [
    "BAE",
  ];
  readonly "IPEW": readonly [
    "IPEW",
  ];
  readonly "IPEP": readonly [
    "IPEP",
  ];
  readonly "IPE": readonly [
    "IPEW",
    "IPEP",
  ];
  readonly "ISEW": readonly [
    "ISEW",
  ];
  readonly "ISEP": readonly [
    "ISEP",
  ];
}>;

export const EXAM_TYPE_SUBJECTS: Readonly<{
  readonly "SQLD": readonly [
    "데이터 모델링의 이해",
    "SQL 기본 및 활용",
  ];
  readonly "SQLP": readonly [
    "데이터 모델링의 이해",
    "SQL 기본 및 활용",
    "SQL 고급 활용 및 튜닝",
  ];
  readonly "DASP": readonly [
    "전사아키텍처 이해",
    "데이터 요건 분석",
    "데이터 표준화",
    "데이터 모델링",
  ];
  readonly "DAP": readonly [
    "전사아키텍처 이해",
    "데이터 요건 분석",
    "데이터 표준화",
    "데이터 모델링",
    "데이터베이스 설계와 이용",
    "데이터 품질 관리 이해",
  ];
  readonly "BAE": readonly [
    "빅데이터 분석기획",
    "빅데이터 탐색",
    "빅데이터 모델링",
    "빅데이터 결과 해석",
  ];
  readonly "IPEW": readonly [
    "소프트웨어 설계",
    "소프트웨어 개발",
    "데이터베이스 구축",
    "프로그래밍 언어 활용",
    "정보시스템 구축 관리",
  ];
  readonly "IPEP": readonly [
    "소프트웨어 설계",
    "소프트웨어 개발",
    "데이터베이스 구축",
    "프로그래밍 언어 활용",
    "정보시스템 구축 관리",
    "정보처리실무",
  ];
  readonly "ISEW": readonly [
    "시스템보안",
    "네트워크보안",
    "어플리케이션보안",
    "정보보안일반",
    "정보보안관리 및 법규",
  ];
  readonly "ISEP": readonly [
    "정보보안 실무",
  ];
}>;

export const EXAM_TYPE_SUBJECT_IDS: Readonly<{
  readonly "SQLD": readonly [
    "data-modeling",
    "sql-basics",
  ];
  readonly "SQLP": readonly [
    "data-modeling",
    "sql-basics",
    "sql-advanced-tuning",
  ];
  readonly "DASP": readonly [
    "enterprise-architecture",
    "data-requirements",
    "data-standardization",
    "data-modeling-practice",
  ];
  readonly "DAP": readonly [
    "enterprise-architecture",
    "data-requirements",
    "data-standardization",
    "data-modeling-practice",
    "database-design-and-use",
    "data-quality-management",
  ];
  readonly "BAE": readonly [
    "big-data-analysis-planning",
    "big-data-exploration",
    "big-data-modeling",
    "big-data-result-interpretation",
  ];
  readonly "IPEW": readonly [
    "ipe-software-design",
    "ipe-software-development",
    "ipe-database-construction",
    "ipe-programming-language-utilization",
    "ipe-information-system-construction-management",
  ];
  readonly "IPEP": readonly [
    "ipe-software-design",
    "ipe-software-development",
    "ipe-database-construction",
    "ipe-programming-language-utilization",
    "ipe-information-system-construction-management",
    "ipe-practical-work",
  ];
  readonly "ISEW": readonly [
    "ise-system-security",
    "ise-network-security",
    "ise-application-security",
    "ise-security-general",
    "ise-security-management-law",
  ];
  readonly "ISEP": readonly [
    "ise-practical-work",
  ];
}>;

export const COURSE_CONTENT_SCOPE_ROWS: readonly [
  Readonly<{
    readonly "examType": "SQLD";
    readonly "contentScope": "SQLD";
  }>,
  Readonly<{
    readonly "examType": "SQLD";
    readonly "contentScope": "both";
  }>,
  Readonly<{
    readonly "examType": "SQLP";
    readonly "contentScope": "SQLP";
  }>,
  Readonly<{
    readonly "examType": "SQLP";
    readonly "contentScope": "both";
  }>,
  Readonly<{
    readonly "examType": "DASP";
    readonly "contentScope": "DASP";
  }>,
  Readonly<{
    readonly "examType": "DASP";
    readonly "contentScope": "DA";
  }>,
  Readonly<{
    readonly "examType": "DAP";
    readonly "contentScope": "DAP";
  }>,
  Readonly<{
    readonly "examType": "DAP";
    readonly "contentScope": "DA";
  }>,
  Readonly<{
    readonly "examType": "BAE";
    readonly "contentScope": "BAE";
  }>,
  Readonly<{
    readonly "examType": "IPEW";
    readonly "contentScope": "IPEW";
  }>,
  Readonly<{
    readonly "examType": "IPEW";
    readonly "contentScope": "IPE";
  }>,
  Readonly<{
    readonly "examType": "IPEP";
    readonly "contentScope": "IPEP";
  }>,
  Readonly<{
    readonly "examType": "IPEP";
    readonly "contentScope": "IPE";
  }>,
  Readonly<{
    readonly "examType": "ISEW";
    readonly "contentScope": "ISEW";
  }>,
  Readonly<{
    readonly "examType": "ISEP";
    readonly "contentScope": "ISEP";
  }>,
];

export const COURSE_SUBJECT_ROWS: readonly [
  Readonly<{
    readonly "examType": "SQLD";
    readonly "subject": "데이터 모델링의 이해";
  }>,
  Readonly<{
    readonly "examType": "SQLD";
    readonly "subject": "SQL 기본 및 활용";
  }>,
  Readonly<{
    readonly "examType": "SQLP";
    readonly "subject": "데이터 모델링의 이해";
  }>,
  Readonly<{
    readonly "examType": "SQLP";
    readonly "subject": "SQL 기본 및 활용";
  }>,
  Readonly<{
    readonly "examType": "SQLP";
    readonly "subject": "SQL 고급 활용 및 튜닝";
  }>,
  Readonly<{
    readonly "examType": "DASP";
    readonly "subject": "전사아키텍처 이해";
  }>,
  Readonly<{
    readonly "examType": "DASP";
    readonly "subject": "데이터 요건 분석";
  }>,
  Readonly<{
    readonly "examType": "DASP";
    readonly "subject": "데이터 표준화";
  }>,
  Readonly<{
    readonly "examType": "DASP";
    readonly "subject": "데이터 모델링";
  }>,
  Readonly<{
    readonly "examType": "DAP";
    readonly "subject": "전사아키텍처 이해";
  }>,
  Readonly<{
    readonly "examType": "DAP";
    readonly "subject": "데이터 요건 분석";
  }>,
  Readonly<{
    readonly "examType": "DAP";
    readonly "subject": "데이터 표준화";
  }>,
  Readonly<{
    readonly "examType": "DAP";
    readonly "subject": "데이터 모델링";
  }>,
  Readonly<{
    readonly "examType": "DAP";
    readonly "subject": "데이터베이스 설계와 이용";
  }>,
  Readonly<{
    readonly "examType": "DAP";
    readonly "subject": "데이터 품질 관리 이해";
  }>,
  Readonly<{
    readonly "examType": "BAE";
    readonly "subject": "빅데이터 분석기획";
  }>,
  Readonly<{
    readonly "examType": "BAE";
    readonly "subject": "빅데이터 탐색";
  }>,
  Readonly<{
    readonly "examType": "BAE";
    readonly "subject": "빅데이터 모델링";
  }>,
  Readonly<{
    readonly "examType": "BAE";
    readonly "subject": "빅데이터 결과 해석";
  }>,
  Readonly<{
    readonly "examType": "IPEW";
    readonly "subject": "소프트웨어 설계";
  }>,
  Readonly<{
    readonly "examType": "IPEW";
    readonly "subject": "소프트웨어 개발";
  }>,
  Readonly<{
    readonly "examType": "IPEW";
    readonly "subject": "데이터베이스 구축";
  }>,
  Readonly<{
    readonly "examType": "IPEW";
    readonly "subject": "프로그래밍 언어 활용";
  }>,
  Readonly<{
    readonly "examType": "IPEW";
    readonly "subject": "정보시스템 구축 관리";
  }>,
  Readonly<{
    readonly "examType": "IPEP";
    readonly "subject": "소프트웨어 설계";
  }>,
  Readonly<{
    readonly "examType": "IPEP";
    readonly "subject": "소프트웨어 개발";
  }>,
  Readonly<{
    readonly "examType": "IPEP";
    readonly "subject": "데이터베이스 구축";
  }>,
  Readonly<{
    readonly "examType": "IPEP";
    readonly "subject": "프로그래밍 언어 활용";
  }>,
  Readonly<{
    readonly "examType": "IPEP";
    readonly "subject": "정보시스템 구축 관리";
  }>,
  Readonly<{
    readonly "examType": "IPEP";
    readonly "subject": "정보처리실무";
  }>,
  Readonly<{
    readonly "examType": "ISEW";
    readonly "subject": "시스템보안";
  }>,
  Readonly<{
    readonly "examType": "ISEW";
    readonly "subject": "네트워크보안";
  }>,
  Readonly<{
    readonly "examType": "ISEW";
    readonly "subject": "어플리케이션보안";
  }>,
  Readonly<{
    readonly "examType": "ISEW";
    readonly "subject": "정보보안일반";
  }>,
  Readonly<{
    readonly "examType": "ISEW";
    readonly "subject": "정보보안관리 및 법규";
  }>,
  Readonly<{
    readonly "examType": "ISEP";
    readonly "subject": "정보보안 실무";
  }>,
];

export function normalizeRegisteredSubjectId(value: unknown): string;
export function registeredSubjectName(value: unknown): string;
export function contentScopeAllowsRegisteredSubject(scope: unknown, subject: unknown): boolean;
export function contentScopeAllowsRegisteredSubjectId(scope: unknown, subjectId: unknown): boolean;
export function normalizeRegisteredExamType(value: unknown): string;
export function normalizeRegisteredContentScope(value: unknown): string;
