// Generated by scripts/generate-course-content-releases.mjs.
// Do not edit this file directly.

export type CourseReleaseStatus = "released" | "blocked";
export type CourseReleaseDefinition = Readonly<{
  courseId: string;
  examType: string;
  fieldId: string;
  linkedQuestionCount: number;
  linkedTheoryCount: number;
  policyVersion: string;
  questionCount: number;
  status: CourseReleaseStatus;
  theoryCount: number;
}>;

export const COURSE_RELEASE_CATALOG_SCHEMA_VERSION: 5;
export const COURSE_CONTENT_RELEASE_VERSION: "learning-2026.09.13.6";
export const COURSE_RELEASE_DEFINITIONS: readonly CourseReleaseDefinition[];
export const RELEASED_EXAM_TYPES: readonly ("SQLD" | "SQLP" | "DASP" | "DAP" | "BAE" | "IPEW" | "IPEP" | "ISEW")[];
export const COURSE_RELEASE_REGISTRY: Readonly<Record<string, CourseReleaseDefinition>>;
export function courseReleaseDefinition(examType: unknown): CourseReleaseDefinition | null;
export function courseReleaseIsReady(examType: unknown): boolean;
