// Generated by scripts/generate-bae-type2.mjs. Do not edit.
export const LOCAL_PRACTICE_TYPE2_RELEASE = {
  "courseId": "bae-practical",
  "capability": "local-practice",
  "stage": "released",
  "version": "2026-09-09-fe878ba71306",
  "prefix": "/content/bae/type2/2026-09-09-fe878ba71306",
  "indexSha256": "7cb3a8ce8e0310eb5b23124d40c80346aa8505a78332b414805ea1ed6af30546",
  "sourceSha256": "cced18655038a41af3d6f5b3534b1b074d08206e4fee44d18d1ad0d3b0309f48",
  "questionCount": 30,
  "moduleCount": 0,
  "datasetCount": 60,
  "checkpointCount": 0
} as const;
