// Generated by scripts/generate-bae-type1.mjs. Do not edit.
export const LOCAL_PRACTICE_RELEASES = [
  {
    "courseId": "bae-practical",
    "capability": "local-practice",
    "stage": "released",
    "version": "2026-09-09-6766be84f668",
    "prefix": "/content/bae/type1/2026-09-09-6766be84f668",
    "indexSha256": "1b7c8570a6a43de8282f025a8839e7ed9b4a5b5ac6e966751fb69a493c89ac55",
    "sourceSha256": "ef23a7790fe98fe26bf1f0b382fe959e8a4afdaa82c4e05de9797a6422971d11",
    "questionCount": 200,
    "moduleCount": 20,
    "datasetCount": 14,
    "checkpointCount": 184
  }
] as const;
