// Generated by scripts/generate-bae-type3.mjs. Do not edit.
export const LOCAL_PRACTICE_TYPE3_RELEASE = {
  "courseId": "bae-practical",
  "capability": "local-practice",
  "stage": "released",
  "version": "2026-09-09-70d4a0472df2",
  "prefix": "/content/bae/type3/2026-09-09-70d4a0472df2",
  "indexSha256": "35efa21888fcbbc7c5e25ff67e066168ddded1fe65269ec5787aa1e5be2541de",
  "sourceSha256": "169667c1b5a041ce2b684d5fd4f64a7b2ec1f3db4aee643974e21a008c0dc411",
  "questionCount": 50,
  "subquestionCount": 150,
  "moduleCount": 0,
  "datasetCount": 50,
  "checkpointCount": 0
} as const;
