// Generated by scripts/generate-sw-curriculum.mjs from sw-curriculum.source.json.
// Do not edit this file directly.

export type SwCurriculumSubjectId = "data-structures" | "algorithms" | "operating-systems" | "computer-architecture" | "database-sql" | "network-data-communication" | "programming-languages" | "software-engineering" | "information-security" | "system-operations" | "it-service-management" | "cloud-devops" | "data-analysis-statistics" | "ai-ml-foundation" | "digital-technology";
export type SwCurriculumSubject = Readonly<{ id: SwCurriculumSubjectId; name: string; summary: string; topics: readonly string[] }>;
export type SwCurriculumSubjectGroup = Readonly<{ id: string; name: string; summary: string; subjects: readonly SwCurriculumSubject[] }>;
export type SwCurriculumRecommendation = Readonly<{ id: string; name: string; summary: string; subjectIds: readonly SwCurriculumSubjectId[]; questionProfileId?: string }>;
export type SwCurriculumQuestionProfile = Readonly<{ id: string; recommendationId: string; subjectIds: readonly SwCurriculumSubjectId[]; requiredTag: string; phaseTags: readonly string[]; selectionMessage: string }>;

export const SW_CURRICULUM_SCHEMA_VERSION: 1;
export const SW_CURRICULUM_FIELD_ID: "software-major";
export const SW_CURRICULUM_CONTENT_SCOPE: "SW";
export const SW_CURRICULUM_SUBJECT_GROUPS: readonly SwCurriculumSubjectGroup[];
export const SW_CURRICULUM_RECOMMENDATIONS: readonly SwCurriculumRecommendation[];
export const SW_CURRICULUM_SUBJECT_IDS: readonly SwCurriculumSubjectId[];
export const SW_CURRICULUM_QUESTION_PROFILES: readonly SwCurriculumQuestionProfile[];
export function swCurriculumQuestionProfile(value: unknown): SwCurriculumQuestionProfile | null;
export function swCurriculumQuestionProfileForSubjects(subjectIds: unknown): SwCurriculumQuestionProfile | null;
