// Generated by scripts/generate-sw-curriculum.mjs from sw-curriculum.source.json.
// Do not edit this file directly.

export type SwCurriculumSummarySubject = Readonly<{ id: string; name: string; summary: string; topics: readonly string[] }>;
export type SwCurriculumSummaryGroup = Readonly<{ id: string; name: string; summary: string; subjects: readonly SwCurriculumSummarySubject[] }>;
export type SwCurriculumSummaryRecommendation = Readonly<{ id: string; name: string; summary: string; subjectIds: readonly string[]; questionProfileId?: string }>;
export const SW_CURRICULUM_SUMMARY_SUBJECT_GROUPS: readonly SwCurriculumSummaryGroup[];
export const SW_CURRICULUM_SUMMARY_RECOMMENDATIONS: readonly SwCurriculumSummaryRecommendation[];
export const SW_CURRICULUM_SUMMARY_SUBJECT_IDS: readonly string[];
