# Generated by scripts/generate-sw-curriculum.mjs from sw-curriculum.source.json.
# Do not edit this file directly.

SUBJECTS = {
    "자료구조": ("computer-science-foundations", "data-structures"),
    "알고리즘": ("computer-science-foundations", "algorithms"),
    "운영체제": ("computer-science-foundations", "operating-systems"),
    "컴퓨터구조": ("computer-science-foundations", "computer-architecture"),
    "데이터베이스·SQL": ("data-and-communication", "database-sql"),
    "네트워크·데이터통신": ("data-and-communication", "network-data-communication"),
    "프로그래밍 언어·객체지향": ("software-development", "programming-languages"),
    "소프트웨어공학·시스템 분석설계": ("software-development", "software-engineering"),
    "정보보안·개인정보보호": ("security-and-operations", "information-security"),
    "시스템 운영·Linux·미들웨어": ("security-and-operations", "system-operations"),
    "IT 서비스·프로젝트·거버넌스": ("security-and-operations", "it-service-management"),
    "클라우드·분산시스템·DevOps": ("security-and-operations", "cloud-devops"),
    "데이터분석·확률통계 기초": ("data-ai-digital-technology", "data-analysis-statistics"),
    "AI·머신러닝·생성형 AI 기초": ("data-ai-digital-technology", "ai-ml-foundation"),
    "디지털 신기술·IT 상식": ("data-ai-digital-technology", "digital-technology"),
}
