-- Generated by scripts/generate-course-registry.mjs from course-registry.source.json.
-- Copy this additive SQL into the next reviewed forward migration; do not edit old migrations.

INSERT OR IGNORE INTO `course_content_scopes` (`exam_type`, `content_scope`)
VALUES
  ('SQLD', 'SQLD'),
  ('SQLD', 'both'),
  ('SQLP', 'SQLP'),
  ('SQLP', 'both'),
  ('DASP', 'DASP'),
  ('DASP', 'DA'),
  ('DAP', 'DAP'),
  ('DAP', 'DA'),
  ('BAE', 'BAE'),
  ('IPEW', 'IPEW'),
  ('IPEW', 'IPE'),
  ('IPEP', 'IPEP'),
  ('IPEP', 'IPE'),
  ('ISEW', 'ISEW'),
  ('ISEP', 'ISEP');
--> statement-breakpoint

INSERT OR IGNORE INTO `course_subjects` (`exam_type`, `subject`)
VALUES
  ('SQLD', '데이터 모델링의 이해'),
  ('SQLD', 'SQL 기본 및 활용'),
  ('SQLP', '데이터 모델링의 이해'),
  ('SQLP', 'SQL 기본 및 활용'),
  ('SQLP', 'SQL 고급 활용 및 튜닝'),
  ('DASP', '전사아키텍처 이해'),
  ('DASP', '데이터 요건 분석'),
  ('DASP', '데이터 표준화'),
  ('DASP', '데이터 모델링'),
  ('DAP', '전사아키텍처 이해'),
  ('DAP', '데이터 요건 분석'),
  ('DAP', '데이터 표준화'),
  ('DAP', '데이터 모델링'),
  ('DAP', '데이터베이스 설계와 이용'),
  ('DAP', '데이터 품질 관리 이해'),
  ('BAE', '빅데이터 분석기획'),
  ('BAE', '빅데이터 탐색'),
  ('BAE', '빅데이터 모델링'),
  ('BAE', '빅데이터 결과 해석'),
  ('IPEW', '소프트웨어 설계'),
  ('IPEW', '소프트웨어 개발'),
  ('IPEW', '데이터베이스 구축'),
  ('IPEW', '프로그래밍 언어 활용'),
  ('IPEW', '정보시스템 구축 관리'),
  ('IPEP', '소프트웨어 설계'),
  ('IPEP', '소프트웨어 개발'),
  ('IPEP', '데이터베이스 구축'),
  ('IPEP', '프로그래밍 언어 활용'),
  ('IPEP', '정보시스템 구축 관리'),
  ('IPEP', '정보처리실무'),
  ('ISEW', '시스템보안'),
  ('ISEW', '네트워크보안'),
  ('ISEW', '어플리케이션보안'),
  ('ISEW', '정보보안일반'),
  ('ISEW', '정보보안관리 및 법규'),
  ('ISEP', '정보보안 실무');
--> statement-breakpoint
